### ISSUE TITLE
[BUG] Error: Unsupported component type: link

### ISSUE THREAD

**Issue by mustafasegf** [itsMapleLeaf/reacord#17]
when clone the reacord-starter and change the return component to link example in https://reacord.mapleleaf.dev/guides/links it errors out to
```
[dev:nodemon] Error: Unsupported component type: link
[dev:nodemon]     at toError (/home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:875:43)
[dev:nodemon]     at raise (/home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:880:9)
[dev:nodemon]     at /home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:1401:9
[dev:nodemon]     at Array.map (<anonymous>)
[dev:nodemon]     at /home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:1377:23
[dev:nodemon]     at Array.map (<anonymous>)
[dev:nodemon]     at getDiscordMessageOptions (/home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:1375:43)
[dev:nodemon]     at Object.reply (/home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:1201:14)
[dev:nodemon]     at InteractionReplyRenderer.createMessage (/home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:1159:29)
[dev:nodemon]     at InteractionReplyRenderer.updateMessage (/home/mustafa/project/new-reacord-app/node_modules/.pnpm/reacord@0.5.0_7ju2jihmv5eytftl4hcdiyvytu/node_modules/reacord/dist/main.cjs:1132:31)
```

**Comment by itsMapleLeaf** [comment]
Thanks for reporting this! A new release for this fix should be up in a bit.
